import random

# creating a dummy LLM class to simulate the behavior of a real LLM
class NakliLLM:

  def __init__(self):
    print('LLM created')

  def predict(self, prompt):

    response_list = [
        'Delhi is the capital of India',
        'IPL is a cricket league',
        'AI stands for Artificial Intelligence'
    ]

    return {'response': random.choice(response_list)}
  
# creating a dummy PromptTemplate class to simulate the behavior of a real PromptTemplate
class NakliPromptTemplate:

  def __init__(self, template, input_variables):
    self.template = template
    self.input_variables = input_variables

  def format(self, input_dict):
    return self.template.format(**input_dict)
  
# creating template to generate a prompt for the LLM 
template = NakliPromptTemplate(
    template='Write a {length} poem about {topic}',
    input_variables=['length', 'topic']
)

# generating a prompt using the template and input variables
prompt = template.format({'length':'short','topic':'india'})
# creating an instance of the dummy LLM class and using it to predict a response based on the generated prompt
llm = NakliLLM()
# printing the response generated by the LLM based on the prompt
print(llm.predict(prompt))


# creating a dummy LLMChain class to simulate the behavior of a real LLMChain
class NakliLLMChain:

  def __init__(self, llm, prompt):
    self.llm = llm
    self.prompt = prompt

  def run(self, input_dict):

    final_prompt = self.prompt.format(input_dict)
    result = self.llm.predict(final_prompt)

    return result['response']

# creating a template to generate a prompt for the LLMChain
template = NakliPromptTemplate(
    template='Write a {length} poem about {topic}',
    input_variables=['length', 'topic']
)

llm = NakliLLM()

chain = NakliLLMChain(llm, template)

print(chain.run({'length':'short', 'topic': 'india'}))